### PR TITLE
fix: issue with page query param for patternhub

### LINKED ISSUE #1949: docs: `page` parameter would get concatenated
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

On opening a URL like https://db-ui.github.io/mono/review/main/components/textarea/overview?page=content, another `page` parameter would get concatenated to the URL if opened through one of the "section" links, which could result in an incorrect URL like e.g. https://db-ui.github.io/mono/review/main/components/textarea/overview?page=content?page=variant%20label

### Expected Behaviour

An existing page parameter from the URL wouldn't be included in the URL if opening the details URL from another "section".

### Screenshots

image

### Browser version

None

### Add any other context about the problem here.

_No response_

### PR DESCRIPTION
**Pull request by nmerget**
## Proposed changes

closes #1949 

## Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Refactoring (fix on existing components or architectural decisions)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation Update (if none of the other choices apply)

### CODE REVIEW

File: showcases/patternhub/components/index.tsx [hunk 1]
```diff
@@ -39,10 +39,21 @@ const DefaultComponent = ({ title, variants }: DefaultComponentProps) => {
...
-			: '';
+	const getHref = (variant: DefaultComponentVariants) => {
+		if (
+			typeof window !== 'undefined' &&
+			window.location.origin &&
+			window?.location?.href
+		) {
+			const url = window.location.href.includes('?')
+				? window.location.href.split('?')[0]
+				: window.location.href;
```
Comment (mfranzke) [inline showcases/patternhub/components/index.tsx:50]:
```suggestion
			const url = window.location.href.split('?')[0];
```

File: showcases/patternhub/components/index.tsx [hunk 2]
```diff
@@ -39,10 +39,21 @@ const DefaultComponent = ({ title, variants }: DefaultComponentProps) => {
...
+
+			return `${url}?page=${variant.name.toLowerCase()}`;
```
Comment (mfranzke) [inline showcases/patternhub/components/index.tsx:52]:
```suggestion
			return `${window.location.href.split('?')[0]}?page=${variant.name.toLowerCase()}`;
```

File: showcases/patternhub/components/index.tsx [hunk 3]
```diff
@@ -39,10 +39,21 @@ const DefaultComponent = ({ title, variants }: DefaultComponentProps) => {
...
 
-	const getHref = (variant: DefaultComponentVariants) =>
-		typeof window !== 'undefined' && window.location.origin
-			? `${window?.location?.href}?page=${variant.name.toLowerCase()}`
-			: '';
+	const getHref = (variant: DefaultComponentVariants) => {
+		if (
+			typeof window !== 'undefined' &&
+			window.location.origin &&
+			window?.location?.href
```
Comment (mfranzke) [inline showcases/patternhub/components/index.tsx:46]: `window.location` should already exist based on the previous codeline.

**Review by mfranzke — APPROVED** [review]
