### PR TITLE
fix: issue with tooltip colors changed by parent component like tag

### LINKED ISSUE #2774: DBTooltip style is overwritten by parent data-emphasis="strong"
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

When using DBTooltip with DBTag (emphasis strong) as parent element, the displayed tooltip inherits is text color from [data-amphasis="strong"]

```html
<DBTag describedbyid="tooltip-01" semantic="neutral" emphasis="strong">
KUZ
<DBTooltip id="tooltip-01" placement="right-end" variant="with arrow">Beschreibungstext</DBTooltip>
</DBTag>
```

### Expected Behaviour

DBTooltip component`s style should not be affected by its parent style.

### Screenshots

_No response_

### Browser version

None

### Add any other context about the problem here.

_No response_

### PR DESCRIPTION
**Pull request by nmerget**
## Proposed changes

closes #2774

## Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Refactoring (fix on existing components or architectural decisions)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation Update (if none of the other choices apply)

### CODE REVIEW

File: showcases/react-showcase/src/components/form/index.tsx [hunk 1]
```diff
@@ -369,6 +370,28 @@ const FormComponent = () => {
 					validMessage="😎"
 					minLength={10}
 				/>
+
+				<DBTag
+					describedbyid="tooltip-01"
+					semantic="neutral"
+					emphasis="strong">
+					KUZ
```
Comment (mfranzke) [inline showcases/react-showcase/src/components/form/index.tsx:378]: https://de.wikipedia.org/wiki/KUZ ?

**Review by mfranzke — APPROVED** [review]

File: showcases/react-showcase/src/components/form/index.tsx (hunk 1 above)
Comment (nmerget) [reply showcases/react-showcase/src/components/form/index.tsx:378]: used the example from the issue, I don't know
