### PR TITLE
fix: issue vue tsc

### LINKED ISSUE #3216: v-components (version 0.3.10): TSC error
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [X] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

The newest v-components version is causing massive problems regarding the types.

By running `vue-tsc --noEmit` you'll get following error:
Bild (4)

This command is fine with version `0.3.5`

This is the underlaying ts config file that has been used for reproduction:

````json
{
	"compilerOptions": {
		"target": "esnext",
		"module": "esnext",
		"strict": true,
		"jsx": "preserve",
		"importHelpers": true,
		"moduleResolution": "node",
		"skipLibCheck": true,
		"esModuleInterop": true,
		"allowSyntheticDefaultImports": true,
		"sourceMap": true,
		"baseUrl": ".",
		"types": [
			"vite/client",
			"vite-plugin-pages/client",
			"vite-plugin-vue-layouts/client"
		],
		"paths": { "@/*": ["src/*"], "@mrr/*": ["../types"] },
		"lib": ["esnext", "dom", "dom.iterable", "scripthost"]
	},
	"include": [
		"src/**/*.vue",
		"src/**/*.js",
		"src/**/*.ts",
		"**/*.ts",
		"src/**/*.d.ts",
		"src/components.d.ts",
		"src/auto-imports.d.ts"
	],
	"exclude": ["node_modules"]
}
````

### Expected Behaviour

No errors would appear.

### Screenshots

_No response_

### Browser version

None

### Add any other context about the problem here.

_No response_

### PR DESCRIPTION
**Pull request by nmerget**
## Proposed changes

closes #3216

## Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Refactoring (fix on existing components or architectural decisions)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation Update (if none of the other choices apply)

### CODE REVIEW

**Review by mfranzke — APPROVED** [review]

File: output/vue/scripts/fix-any-types.ts [hunk 1]
```diff
@@ -22,15 +22,18 @@ const replaceAnyTypes = (input: string, component: string) => {
...
+				// Check if prop(contains ": any") or function
+				if (propLine.includes(': any;')) {
+					const prop = propLine
+						.replace('?: any;', '')
+						.replace(': any;', '')
+						.trim();
+					// @ts-ignore
+					fileContent = fileContent.replaceAll(
+						propLine,
+						propLine.replace('any', `${propModel}["${prop}"]`)
```
Comment (mfranzke) [inline output/vue/scripts/fix-any-types.ts:34]: this looks a little global in the end already, let's reinvestigate on this.
