### PR TITLE
fix: issue with invalid message not showing

### LINKED ISSUE #2957: CSS :is([data-semantic, :empty) not working
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [X] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

@db-ui/react-components v0.2.5

		<DBInput
				label="Test label"
				variant="floating"
				invalidMessage="Test message"
				validMessage=""
			/>

### Expected Behaviour

The "Test message" is supposed to be visible on screen, but it is not. The guilty part is this CSS selector: `.db-input .db-infotext:is([data-semantic], :empty)`.
A CSS selector that works: `.db-input .db-infotext[data-semantic]:empty`.

### Screenshots

image

### Browser version

None

### Add any other context about the problem here.

_No response_

### PR DESCRIPTION
**Pull request by nmerget**
## Proposed changes

invalid message not showing `:is([data-semantic], :empty)`

`:empty` is not necessary, as the regular message wouldn't get rendered at all of left empty.

closes #2957 

## Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Refactoring (fix on existing components or architectural decisions)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation Update (if none of the other choices apply)

### CODE REVIEW

**Review by mfranzke — APPROVED** [review]

**Review by bruno-sch — DISMISSED** [review]

**Review by mfranzke — APPROVED** [review]

**Review by mfranzke — DISMISSED** [review]

File: showcases/screen-reader/default.ts [hunk 1]
```diff
@@ -35,7 +35,8 @@ const standardPhrases = [
 const flakyExpressions: Record<string, string> = {
 	'pop-up': 'pop up',
 	'checked. checked': 'checked',
-	'selected. selected': 'selected'
+	'selected. selected': 'selected',
+	'expanded. expanded': 'selected'
```
Comment (mfranzke) [inline showcases/screen-reader/default.ts:39]:
```suggestion
	'expanded. expanded': 'expanded'
```

this needs to be _expanded_, doesn't it ?

Comment (nmerget) [reply showcases/screen-reader/default.ts]: I'm not sure :(

Comment (mfranzke) [reply showcases/screen-reader/default.ts]: 🤫

**Review by mfranzke — APPROVED** [review]
