### PR TITLE
fix: issue with drawer closing on every key

### LINKED ISSUE #2594: db-drawer: onClose event fires on every key event.
### Which generators are impacted?

- [X] All
- [ ] HTML
- [X] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

Open Drawer: https://db-ui.github.io/mono/review/main/components/drawer/overview
and press any key. Drawer is closed on every KeyEvent.

### Expected Behaviour

1. Automatic closing only on specific KeyEvent e.g. "escape" OR
2. provide KeyEvent to props.onClose to enable users to react to different cases ...

### Screenshots

_No response_

### Browser version

None

### Add any other context about the problem here.

_No response_

### PR DESCRIPTION
**Pull request by nmerget**
## Proposed changes

closes #2594

- Handle backdrop click with additional `event.type===click`
- Pass `event` to `onClose` for user to check which event was fired

## Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Refactoring (fix on existing components or architectural decisions)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation Update (if none of the other choices apply)

### CODE REVIEW

File: packages/components/src/components/drawer/model.ts [hunk 1]
```diff
@@ -8,18 +8,22 @@ import {
 } from '../../shared/model';
 
 export interface DBDrawerDefaultProps {
+	/**
+	 * The backdrop attribute changes the opacity of the backdrop.
+	 * The backdrop 'none' will use `dialog.show()` instead of `dialog.showModal()`
+	 */
```
Comment (annsch) [inline packages/components/src/components/drawer/model.ts:14]: good to know ;)

**Review by annsch — APPROVED** [review]

**Comment by annsch** [comment]
@nmerget what this pr not fixes is the case of clicking any key leading to close the drawer. Is this behaviour intentional by @db-ui?

**Comment by nmerget** [comment]
> @nmerget what this pr not fixes is the case of clicking any key leading to close the drawer. Is this behaviour intentional by @db-ui?

No this is an issue, thought it was solved
