### PR TITLE
fix(input): filled icons for inputstate

### LINKED ISSUE #293: fix: icons for input field
- [ ] icons for data-variants should contain filled icons
- [ ] invalid input does not include the error icon when input field is aria-invalid

### PR DESCRIPTION
**Pull request by annsch**
closes #293

### CODE REVIEW

**Review by mfranzke — APPROVED** [review]

File: showcases/react-showcase/src/components/input/index.tsx [hunk 1]
```diff
@@ -82,6 +82,16 @@ const variants: DefaultComponentVariants[] = [
 					/>
 				)
 			},
+			{
+				name: 'Invalid',
+				example: (
+					<DBInput
+						label="MinLength = 5"
```
Comment (mfranzke) [inline showcases/react-showcase/src/components/input/index.tsx:89]: what about adding this as description instead ?

Comment (annsch) [reply showcases/react-showcase/src/components/input/index.tsx]: fixed

**Review by mfranzke — APPROVED** [review]
